/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "date.h"

bool_t
xdr_sntp (XDR *xdrs, sntp *objp)
{
//	register int *buf;

	 if (!xdr_SNTP_PARTIAL (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_SNTP_PARTIAL (XDR *xdrs, SNTP_PARTIAL *objp)
{
	register int *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->ref))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->org))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->rec))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->xmt))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->dst))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->delay))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyid))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->type);
			IXDR_PUT_LONG(buf, objp->ref);
			IXDR_PUT_LONG(buf, objp->org);
			IXDR_PUT_LONG(buf, objp->rec);
			IXDR_PUT_LONG(buf, objp->xmt);
			IXDR_PUT_LONG(buf, objp->dst);
			IXDR_PUT_LONG(buf, objp->delay);
			IXDR_PUT_LONG(buf, objp->offset);
			IXDR_PUT_U_LONG(buf, objp->keyid);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->ref))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->org))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->rec))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->xmt))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->dst))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->delay))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->offset))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyid))
				 return FALSE;
		} else {
			objp->type = IXDR_GET_LONG(buf);
			objp->ref = IXDR_GET_LONG(buf);
			objp->org = IXDR_GET_LONG(buf);
			objp->rec = IXDR_GET_LONG(buf);
			objp->xmt = IXDR_GET_LONG(buf);
			objp->dst = IXDR_GET_LONG(buf);
			objp->delay = IXDR_GET_LONG(buf);
			objp->offset = IXDR_GET_LONG(buf);
			objp->keyid = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->ref))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->org))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->rec))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->xmt))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->dst))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->delay))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyid))
		 return FALSE;
	return TRUE;
}
